steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --build-arg=BUNDLE_OPTIONS=--without development test
    - --destination=gcr.io/<Google Cloud Platform Project ID>/<Container Image Name>:latest
    - --cache=true
