steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --build-arg=BUNDLE_OPTIONS=--without development test
    - --destination=gcr.io/cloudrun-connection-redis/cloudrun-redis:latest
    - --cache=true
