version: '3'
services:
  app: &app_base
    build:
      context: .
    command: 'bin/start'
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    tty: true
    stdin_open: true
  redis:
    image: redis:4-alpine
